#!/bin/sh

# 清理未有用的内容
rm ./go.mod
rm ./main.go
rm temp

# 声明transfer环境变量配置
export TRANSFER_CONSUL_HTTP_PORT = ${BK_CONSUL_HTTP_PORT}
export TRANSFER_CONSUL_HTTPS_PORT = ${BK_CONSUL_HTTPS_PORT}
export TRANSFER_CONSUL_TLS_CA_FILE = ${BK_CONSUL_SERVER_CA_CERT}
export TRANSFER_CONSUL_TLS_KEY_FILE = ${BK_CONSUL_CLIENT_KEY_FILE}
export TRANSFER_CONSUL_TLS_CERT_FILE = ${BK_CONSUL_CLIENT_CERT_FILE}
export TRANSFER_ESB_ADDRESS = ${BK_PAAS_PRIVATE_URL}
export TRANSFER_ESB_BK_APP_CODE = ${BK_MONITOR_APP_CODE}
export TRANSFER_ESB_BK_APP_SECRET = ${BK_MONITOR_APP_SECRET}
export TRANSFER_HTTP_HOST = ${LAN_IP}
export TRANSFER_HTTP_PORT = ${BK_TRANSFER_HTTP_PORT}
export TRANSFER_HTTP_AUTH_TOKEN = "${BK_MONITOR_APP_CODE}:${BK_MONITOR_APP_SECRET}"
export TRANSFER_LOGGER_OUT_OPTIONS_FILE = "${BK_HOME}/logs/bkmonitorv3/transfer.log"
export TRANSFER_STORAGE_PATH = "${BK_HOME}/public/bkmonitorv3/transfer"